// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the act was. Places are named as navigation names them; `from` is `None` when the files
 * came from more than one folder, and `one` names the file when there was only one.
 */
export type Act = { "kind": "move", from: string | null, to: string, one: string | null, } | { "kind": "moveFolder", name: string, from: string, to: string, } | { "kind": "delete", from: string | null, one: string | null, } | { "kind": "renameFile", from: string, to: string, } | { "kind": "renameFolder", from: string, to: string, } | { "kind": "createFolder", name: string, parent: string, } | { "kind": "restore", to: string | null, one: string | null, } | { "kind": "deleteFolder", name: string, parent: string, into: string | null, };
