// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Refusal } from "./Refusal";
import type { Source } from "./Source";

/**
 * What came of offering the app a folder. A refusal is an answer, not an error:
 * nothing is added, nothing is selected, and the band says which of the four it
 * was. DECISIONS.md "Places, not queries".
 */
export type AddOutcome = { "kind": "added", source: Source, } | { "kind": "refused", why: Refusal, clash: string | null, };
