// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Act } from "./Act";

/**
 * One act, and how many files and folders it holds.
 */
export type Batch = { batchId: string, act: Act, 
/**
 * Every file the act carried, those inside a moved folder included.
 */
files: number, folders: number, };
