// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the files in a folder being deleted go. PRODUCT.md "Folders and sources".
 */
export type Contents = { "kind": "trash" } | { "kind": "moveTo", sourceId: number, };
