// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A picture the cover can be, as the picker offers it.
 */
export type CoverChoice = { itemId: number, 
/**
 * Its thumbnail, once made. Filled by the command.
 */
thumb: string | null, };
