// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder on the way down from a source's own folder, as the breadcrumb takes it.
 */
export type Crumb = { id: number, title: string, };
