// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stayed } from "./Stayed";

/**
 * Whether a folder went, and what kept it when it did not.
 */
export type DeleteReport = { deleted: boolean, refused: Array<Stayed>, };
