// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";

/**
 * A digit bound to a folder, as navigation, Settings and a press read it: the way down to the
 * folder, the files directly in it, and whether it is gone or its source is away.
 */
export type DestinationKey = { 
/**
 * One digit, `0` to `9`.
 */
key: string, folderId: number, sourceId: number, 
/**
 * From the source's own folder, by the source's title, down to the folder, gone or not.
 */
path: Array<Crumb>, itemCount: number, 
/**
 * Retired by a delete or a walk; the key stays, since an undo can bring the folder back.
 */
gone: boolean, reachable: boolean, };
