// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type EffectiveTag = { tagId: number, key: string | null, value: string, 
/**
 * The folder it came from, or `None` when the item carries it itself.
 */
originId: number | null, originTitle: string | null, };
