// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One failed job, named by the file it was about, with what went wrong.
 */
export type Failure = { jobId: number, kind: string, name: string, error: string, attempts: number, };
