// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The field says each in its own words. Components › "The field holds the query".
 */
export type Fault = { "kind": "empty" } | { "kind": "unclosedGroup", after: string | null, } | { "kind": "unopenedGroup" } | { "kind": "unclosedQuote", before: string | null, } | { "kind": "badValue", key: string, value: string, } | { "kind": "missingTerm" };
