// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";

/**
 * A favourite place as navigation's group shows it: the way down to it, the files directly in
 * it, and whether its source can be read.
 */
export type FavouritePlace = { folderId: number, sourceId: number, 
/**
 * From the source's own folder, by the source's title, down to the place.
 */
path: Array<Crumb>, itemCount: number, reachable: boolean, };
