// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";

/**
 * A tag or a label on a folder: a label has a key.
 */
export type FolderTag = { tagId: number, key: string | null, value: string, 
/**
 * The folder above that carries it, or `None` when this folder does.
 */
from: Crumb | null, 
/**
 * A folder's name, which only renaming it changes.
 */
name: boolean, };
