// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Matched } from "./Matched";

/**
 * A folder the query found, and the term that found it.
 */
export type FolderMatch = { id: number, sourceId: number, title: string, 
/**
 * The folders above it, its source's first.
 */
above: Array<string>, 
/**
 * Every live file at or below it.
 */
count: number, 
/**
 * The picture that stands for it, once its thumbnail is made. Filled by the command.
 */
cover: string | null, matched: Matched, };
