// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder as the navigation lists it. Counts are of live, direct contents.
 */
export type FolderNode = { id: number, title: string, childCount: number, itemCount: number, favorite: boolean, };
