// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A live folder anywhere in the library, as a picker lays out the whole tree at once.
 */
export type FolderEntry = { id: number, 
/**
 * `None` for a source's own folder.
 */
parentId: number | null, sourceId: number, 
/**
 * A source's own folder goes by the source's title, as navigation shows it.
 */
title: string, };
