// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder the app made, and the batch that undoes it.
 */
export type FolderMade = { folderId: number, batchId: string, };
