// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { FolderStatus } from "./FolderStatus";
import type { FolderTag } from "./FolderTag";

/**
 * A folder as its band shows it.
 */
export type FolderDetail = { id: number, sourceId: number, 
/**
 * From its source's own folder, by the source's title, down to it.
 */
path: Array<Crumb>, status: FolderStatus | null, statusSetAt: number | null, favorite: boolean, note: string | null, 
/**
 * The file chosen as its cover, while that file is live at or below it.
 */
coverItemId: number | null, 
/**
 * The picture that stands for it, once its thumbnail is made. Filled by the command.
 */
cover: string | null, 
/**
 * The live files directly in it, then every one at or below it.
 */
ownCount: number, allCount: number, 
/**
 * Its own first, its name leading, then what it inherits, the source's first.
 */
tags: Array<FolderTag>, };
