// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { Matched } from "./Matched";

/**
 * A folder the query found, and the term that found it.
 */
export type FolderMatch = { id: number, sourceId: number, title: string, 
/**
 * From its source's own folder, by the source's title, down to it, as a place is named.
 */
path: Array<Crumb>, 
/**
 * Every live file at or below it.
 */
count: number, 
/**
 * The picture that stands for it, once its thumbnail is made. Filled by the command.
 */
cover: string | null, matched: Matched, };
