// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeleteReport } from "./DeleteReport";

/**
 * What deleting a folder did, and the batch that undoes whatever of it happened.
 */
export type FolderDeleted = { batchId: string | null, report: DeleteReport, };
