// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folder as the navigation lists it. Counts are of live contents: its own, then everything at
 * or below it.
 */
export type FolderNode = { id: number, title: string, childCount: number, itemCount: number, allCount: number, favorite: boolean, };
