// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";

/**
 * A file a search found, the folder it lives in or, in the Trash, the one it left, and when it
 * went there.
 */
export type Hit = { at: Origin, trashedAt: number | null, id: number, uuid: string, folderId: number, diskName: string, ext: string, kind: "image" | "video" | "other", sizeBytes: number, mtime: number, width: number | null, height: number | null, durationMs: number | null, favorite: boolean, 
/**
 * The thumbnail's path, once one has been made.
 */
thumb: string | null, };
