// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MoveReport } from "./MoveReport";

/**
 * What a move of files did, and the batch that undoes it when anything went.
 */
export type ItemsMoved = { batchId: string | null, report: MoveReport, };
