// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Batch } from "./Batch";
import type { TrashReport } from "./TrashReport";

/**
 * What sending files to the trash did, and the batch that undoes it when anything went.
 */
export type ItemsTrashed = { batch: Batch | null, report: TrashReport, };
