// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Batch } from "./Batch";
import type { RestoreReport } from "./RestoreReport";

/**
 * What restoring files did, and the batch that undoes it when anything came back.
 */
export type ItemsRestored = { batch: Batch | null, report: RestoreReport, };
