// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Crumb } from "./Crumb";
import type { SourceKind } from "./SourceKind";

/**
 * One item in full, as the pane shows it.
 */
export type ItemDetail = { codec: string | null, bitrate: number | null, 
/**
 * Seconds since 1970; from EXIF, the camera's clock read as UTC. DECISIONS.md "Capture dates".
 */
capturedAt: number | null, capturedSrc: "exif" | "container" | null, addedAt: number, sourceId: number, sourceKind: SourceKind, 
/**
 * From the source's own folder down to the item's.
 */
folders: Array<Crumb>, 
/**
 * The file, for the window to load. Empty until the command layer fills it in.
 */
path: string, id: number, uuid: string, folderId: number, diskName: string, ext: string, kind: "image" | "video" | "other", sizeBytes: number, mtime: number, width: number | null, height: number | null, durationMs: number | null, favorite: boolean, 
/**
 * The thumbnail's path, once one has been made.
 */
thumb: string | null, };
