// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An item as the grid lists it.
 */
export type ItemRow = { id: number, uuid: string, folderId: number, diskName: string, ext: string, kind: "image" | "video" | "other", sizeBytes: number, mtime: number, width: number | null, height: number | null, durationMs: number | null, favorite: boolean, };
