// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A label's key or a value of one the library already has, with how many folders carry it.
 */
export type LabelOffer = { text: string, folders: number, };
