// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a folder matched on, said key first. PRODUCT.md "Tags and labels".
 */
export type Matched = { "kind": "name", value: string, } | { "kind": "tag", value: string, } | { "kind": "label", key: string, value: string, };
