// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stayed } from "./Stayed";

/**
 * What a move of several items did: how many went, and each one that did not, with why.
 */
export type MoveReport = { moved: number, refused: Array<Stayed>, };
