// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The folder a trashed file left, named from its source's own folder down. `gone` when neither
 * it nor a folder at its place is live, so Restore would be refused.
 */
export type Origin = { folderId: number, path: Array<string>, gone: boolean, };
