// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Phase } from "./Phase";

export type Progress = { phase: Phase, pending: number, running: number, failed: number, 
/**
 * Jobs finished since launch.
 */
completed: number, };
