// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";

/**
 * One part of the query's top-level AND, and where in the text it was typed, counted in UTF-16
 * units as the field counts.
 */
export type QueryTerm = { 
/**
 * The part as text that reads back as itself.
 */
text: string, shape: Shape, start: number, end: number, };
