// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Fault } from "./Fault";

export type QueryFault = { why: Fault, 
/**
 * Where it starts, in UTF-16 units.
 */
at: number, };
