// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryFault } from "./QueryFault";
import type { QueryTerm } from "./QueryTerm";

/**
 * What the field understood of its text: the terms read, and why the rest did not read.
 */
export type Reading = { terms: Array<QueryTerm>, fault: QueryFault | null, };
