// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a folder was not taken as a source. The words belong to the band that says
 * so; this only says which of the four it was. DESIGN.md "Shapes".
 */
export type Refusal = "same" | "inside" | "contains" | "appFolder";
