// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stayed } from "./Stayed";

/**
 * What restoring several items did: how many came back, and each one that did not, with why.
 */
export type RestoreReport = { restored: number, refused: Array<Stayed>, };
