// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FolderMatch } from "./FolderMatch";
import type { Hit } from "./Hit";
import type { QueryFault } from "./QueryFault";
import type { QueryTerm } from "./QueryTerm";

/**
 * A search's answer: its terms, the folders and then the files it found; or why it did not read.
 */
export type SearchOutcome = { "kind": "found", terms: Array<QueryTerm>, folders: Array<FolderMatch>, items: Array<Hit>, } | { "kind": "unparsed", fault: QueryFault, };
