// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The shape a part takes in the field: a folder, a place, a tag and a label as the details draw
 * them, and anything else as the words it was typed as.
 */
export type Shape = { "kind": "path", titles: Array<string>, exact: boolean, } | { "kind": "place", place: "sorting" | "trash", } | { "kind": "tag", value: string, } | { "kind": "label", key: string, value: string, } | { "kind": "text" };
