// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

export type Source = { id: number, root: string, title: string, kind: SourceKind, addedAt: number, 
/**
 * When a walk last read all of it; `None` until the first one finishes.
 */
indexedAt: number | null, };
