// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SourceKind } from "./SourceKind";

/**
 * A source as the navigation and Settings show it.
 */
export type SourceSummary = { rootFolderId: number, 
/**
 * False when its directory cannot be read — an unplugged drive, say.
 */
reachable: boolean, itemCount: number, totalBytes: number, id: number, root: string, title: string, kind: SourceKind, addedAt: number, };
