// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Reason } from "./Reason";
import type { Thing } from "./Thing";
import type { Whereabouts } from "./Whereabouts";

/**
 * One file or folder that stayed where it was, and why.
 */
export type Stayed = { kind: Thing, id: number, name: string, at: Whereabouts, reason: Reason, };
