// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Shape } from "./Shape";
import type { SuggestionKind } from "./SuggestionKind";

/**
 * One row of the list: the term it writes, and how the row draws it.
 */
export type Suggestion = { kind: SuggestionKind, 
/**
 * The term as text that reads back as itself, with the `-` the word was typed with.
 */
text: string, shape: Shape, 
/**
 * A folder's titles from the scope down to it, or from its source with no scope.
 */
path: Array<string>, };
