// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Suggestion } from "./Suggestion";

/**
 * The list under the field: where the word being typed starts, and the terms offered for it.
 */
export type Suggestions = { 
/**
 * In UTF-16 units. A pick replaces the text from here to its end.
 */
from: number, rows: Array<Suggestion>, };
