// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A tag the library already has, offered while one is typed, with how many files carry it.
 */
export type TagOffer = { value: string, files: number, };
