// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Origin } from "./Origin";

/**
 * A file in the trash, when it went, and the folder it left.
 */
export type Trashed = { trashedAt: number, from: Origin, id: number, uuid: string, folderId: number, diskName: string, ext: string, kind: "image" | "video" | "other", sizeBytes: number, mtime: number, width: number | null, height: number | null, durationMs: number | null, favorite: boolean, 
/**
 * The thumbnail's path, once one has been made.
 */
thumb: string | null, };
