// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Refused } from "./Refused";

/**
 * What sending several items to the trash did: how many went, and each one that did not, with why.
 */
export type TrashReport = { trashed: number, refused: Array<Refused>, };
