// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Batch } from "./Batch";
import type { Stayed } from "./Stayed";

/**
 * The act an undo took back, how much of it came back, and what could not, each with where it
 * still is and why.
 */
export type UndoReport = { batch: Batch, filesBack: number, foldersBack: number, stayed: Array<Stayed>, };
