// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an undo put back, and what it could not, each with its reason.
 */
export type UndoReport = { reversed: number, errors: Array<string>, };
