// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Stayed } from "./Stayed";

/**
 * What an undo put back, and what it could not, each with where it still is and why.
 */
export type UndoReport = { reversed: number, stayed: Array<Stayed>, };
