// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WalkReport = { 
/**
 * Files whose row already matched — the cheap path.
 */
unchanged: number, 
/**
 * Files recorded for the first time, or refreshed because they changed.
 */
indexed: number, 
/**
 * Items retired because the walk never found their file.
 */
itemsRetired: number, 
/**
 * Folders retired because their directory is gone.
 */
foldersRetired: number, };
