// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where something that stayed is now: a folder, named from its source's own folder down, or
 * the app's trash.
 */
export type Whereabouts = { "kind": "folder", folderId: number, path: Array<string>, } | { "kind": "trash" };
